# ══════════════════════════════════════════════════════════════════════════════
#  Autostart Daemons & Background Services (~/.config/hypr/conf/autostart.conf)
# ══════════════════════════════════════════════════════════════════════════════

# Polkit Authentication Agent
exec-once = systemctl enable --now --user hyprpolkitagent

# Clipboard History Daemons
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
