# ══════════════════════════════════════════════════════════════════════════════
#  Window Rules (~/.config/hypr/conf/rules.conf)
# ══════════════════════════════════════════════════════════════════════════════

windowrulev2 = suppressevent maximize, class:.*
windowrulev2 = float, title:^(Picture-in-Picture|Picture in picture)$
windowrulev2 = pin, title:^(Picture-in-Picture|Picture in picture)$
windowrulev2 = float, class:^(pavucontrol|nm-connection-editor|blueman-manager|swappy)$
